name: CI/CD Workflow

on: [push]

env:
  WORKON_HOME: /home/runner/.local/share/virtualenvs
  REPOSITORY_NAME: ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}

jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
        cache: 'pipenv'
        cache-dependency-path: |
          Pipfile.lock
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev

  security-check:
    name: セキュリティチェック
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: snyk/actions/setup@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
        cache: 'pipenv'
        cache-dependency-path: |
          Pipfile.lock
    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv update
        pipenv requirements --dev > requirements.txt
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 30
    - name: Snyk test
      continue-on-error: true
      run: |
        snyk test --sarif-file-output=snyk.sarif --severity-threshold=high
        snyk code test --sarif-file-output=snyk_code.sarif --severity-threshold=high
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Upload snyk test result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif
    - name: Upload snyk code test result to GitHub Code Scanning
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk_code.sarif
