name: CI/CD Workflow

on: [push]

env:
  WORKON_HOME: /home/runner/.local/share/virtualenvs
  REPOSITORY_NAME: ${GITHUB_REPOSITORY#${GITHUB_REPOSITORY_OWNER}/}

jobs:
  build:
    name: ビルド
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
        cache: 'pipenv'
        cache-dependency-path: |
          Pipfile.lock
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv sync --dev

  security-check:
    name: セキュリティチェック
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - uses: snyk/actions/setup@master
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10.13'
        cache: 'pipenv'
        cache-dependency-path: |
          Pipfile.lock
    - name: Install pipenv
      run: |
        pip install pipenv
        pipenv requirements --dev > requirements.txt
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 30
    - name: Snyk monitor
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    # - name: Run Snyk to check for vulnerabilities
    #   uses: snyk/actions/python-3.10@master
    #   env:
    #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
